---
name: Install Just
description: Install Just from Github Release
runs:
  using: "composite"
  steps:
    - name: Install Just
      shell: bash
      run: |-
        set -eoux pipefail
        while [[ "${JUST_VERSION:-}" =~ null || -z "${JUST_VERSION:-}" ]]
        do
          JUST_VERSION=$( \
            curl --fail --retry 5 --retry-delay 5 --retry-all-errors -sL \
                https://api.github.com/repos/casey/just/releases/latest |
            jq -r '.tag_name')
        done
        ARCH=$(uname -m)
        case "${ARCH}" in
          aarch64) TARGET="aarch64-unknown-linux-musl" ;;
          *)       TARGET="x86_64-unknown-linux-musl" ;;
        esac
        URL="https://github.com/casey/just/releases/download"
        TARGZ="just-${JUST_VERSION}-${TARGET}.tar.gz"
        curl --fail --retry 5 --retry-delay 5 --retry-all-errors -sSLO \
          ${URL}/${JUST_VERSION}/${TARGZ}
        tar -zxvf ${TARGZ} -C /tmp just
        sudo mv /tmp/just /usr/local/bin/just
        rm -f ${TARGZ}
