name: bOS Build Server
on:
  schedule:
    - cron: "11 6 * * 0" # 6:31 UTC Sunday
    - cron: "11 6 * * 1,2,3,4,5,6" # 6:31 UTC Monday-Saturday
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-image:
    name: Build Images
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        image_flavor: ["Server"]
    with:
      image_flavor: ${{ matrix.image_flavor }}

