name: bOS Build Server
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_call:
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: bos
  IMAGE_STYLED: bOS

jobs:
  push-ucore:
    name: Build Ucore Images
    runs-on: ubuntu-24.04
    continue-on-error: false
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image:
          - ucore-minimal
          - ucore
          - ucore-hci
        tag:
          - stable
          - testing
        flavor:
          - main
          - nvidia
        exclude:
          - image: ucore-minimal
            tag: testing
          - image: ucore
            tag: testing
          - image: ucore-minimal
            flavor: nvidia
          - image: ucore-hci
            flavor: nvidia
    steps:
      - name: Checkout Push to Registry Action
        uses: actions/checkout@v4

      - name: Setup Just
        id: setup_just
        shell: bash
        run: |
          cd /usr/bin && \
              sudo curl -sSLO \
                  https://github.com/casey/just/releases/download/1.36.0/just-1.36.0-x86_64-unknown-linux-musl.tar.gz && \
              sudo tar -zxvf just-1.36.0-x86_64-unknown-linux-musl.tar.gz just && \
              sudo rm -f just-1.36.0-x86_64-unknown-linux-musl.tar.gz

      - name: Get Source Image Info
        id: source_info
        shell: bash
        run: |
          build_src_dst=($(just gen-build-src-dst "${{ matrix.image }}" "${{ matrix.tag }}" "${{ matrix.flavor }}"))
          src_img=${build_src_dst[0]}
          src_tag=${build_src_dst[1]}

          echo "source_image=${src_img}" >> "$GITHUB_ENV"
          echo "source_tag=${src_tag}" >> "$GITHUB_ENV"

      - name: Generate Tags
        id: generate_tags
        shell: bash
        run: |
          TIMESTAMP="$(date +%Y%m%d)"

          # Validate is handled by gen-build-src-dst
          build_src_dst=($(just gen-build-src-dst "${{ matrix.image }}" "${{ matrix.tag }}" "${{ matrix.flavor }}"))
          tag=${build_src_dst[3]}

          BUILD_TAGS+=("${tag}" "${tag}-${TIMESTAMP}")
          for TAG in "${BUILD_TAGS[@]}"; do
            echo "${TAG}"
          done
          echo "image=${tag}" >> "$GITHUB_ENV"
          echo "default_tag=${tag}" >> "$GITHUB_OUTPUT"
          echo "build_tags=${BUILD_TAGS[*]}" >> "$GITHUB_OUTPUT"

      - name: Verify Source Image
        uses: EyeCantCU/cosign-action/verify@58722a084c82190b57863002d494c91eabbe9e79 # v0.3.0
        with:
          containers: ${{ env.source_image }}:${{ env.source_tag }}

      - name: Maximize Build Space
        uses: ublue-os/remove-unwanted-software@v7

      - name: Pull Images
        uses: Wandalen/wretry.action@v3.7.0
        id: pull
        with:
          attempt_limit: 3
          attempt_delay: 15000
          command: |
            set -eoux pipefail
            sudo podman pull ghcr.io/ublue-os/${{ env.source_image }}:${{ env.source_tag }}

      - name: Build Image
        id: build_image
        shell: bash
        run: |
          sudo just build "${{ matrix.image }}" "${{ matrix.tag }}" "${{ matrix.flavor }}"

      - name: Rechunk Image
        id: rechunk
        shell: bash
        run: |
          sudo just rechunk "${{ matrix.image }}" "${{ matrix.tag }}" "${{ matrix.flavor }}"

      - name: Load into Podman and Tag
        shell: bash
        run: |
          set -eoux pipefail
          sudo podman images
          podman images
          IMAGE="localhost/${{ env.source_image }}:${{ env.source_tag }}"
          for tag in ${{ steps.generate_tags.outputs.build_tags }}; do
            podman tag $IMAGE ${{ env.IMAGE_NAME }}:$tag
          done
          podman tag $IMAGE rechunked-img

      - name: Check Secureboot
        id: secureboot
        shell: bash
        run: |
          set -x
          if [[ ! $(command -v sbverify) || ! $(command -v curl) || ! $(command -v openssl) ]]; then
            sudo apt update
            sudo apt install sbsigntool curl openssl
          fi
          TMP=$(podman create rechunked-img bash)
          podman cp $TMP:/usr/lib/modules/${{ env.kernel_release }}/vmlinuz .
          podman rm $TMP
          sbverify --list vmlinuz
          curl --retry 3 -Lo kernel-sign.der https://github.com/ublue-os/kernel-cache/raw/main/certs/public_key.der
          curl --retry 3 -Lo akmods.der https://github.com/ublue-os/kernel-cache/raw/main/certs/public_key_2.der
          openssl x509 -in kernel-sign.der -out kernel-sign.crt
          openssl x509 -in akmods.der -out akmods.crt
          sbverify --cert kernel-sign.crt vmlinuz || exit 1
          sbverify --cert akmods.crt vmlinuz || exit 1

      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      - name: Push to GHCR
        uses: Wandalen/wretry.action@v3.7.0
        id: push
        if: github.event_name != 'pull_request'
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          action: redhat-actions/push-to-registry@v2
          attempt_limit: 3
          attempt_delay: 15000
          with: |
            image: ${{ env.IMAGE_NAME }}
            tags: ${{ steps.generate_tags.outputs.build_tags }}
            registry: ${{ steps.registry_case.outputs.lowercase }}
            username: ${{ env.REGISTRY_USER }}
            password: ${{ env.REGISTRY_PASSWORD }}
            extra-args: |
              --disable-content-trust

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: sigstore/cosign-installer@v3.7.0
        if: github.event_name != 'pull_request'

      - name: Sign Container Image
        if: github.event_name != 'pull_request'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ steps.registry_case.outputs.lowercase }}/${{ env.IMAGE_NAME }}@${TAGS}
        env:
          TAGS: ${{ steps.push.outputs.outputs && fromJSON(steps.push.outputs.outputs).digest }}
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}

      - name: Echo Outputs
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
