---
name: bOS Build Desktop
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "41 6 * * 5"  # 6:41 UTC Friday
    - cron: "41 6 * * 0,1,2,3,4,6"  # 6:41 UTC Sunday-Thursday, Saturday
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".editorconfig"
      - ".gitignore"
      - "yamlfmt.yml"
      - ".github/renovate.json"
      - ".github/semantic.yml"
      - ".claude/**"
      - ".github/workflows/cleanup-old-images.yml"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".editorconfig"
      - ".gitignore"
      - "yamlfmt.yml"
      - ".github/renovate.json"
      - ".github/semantic.yml"
      - ".claude/**"
      - ".github/workflows/cleanup-old-images.yml"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: write
  packages: write
  id-token: write
jobs:
  build-image:
    name: Build Images
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        image_flavor: ["Bazzite"]
    with:
      image_flavor: ${{ matrix.image_flavor }}
      publish_schedule: '41 6 * * 5'
