name: bOS Build Server
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "11 6 * * 0" # 6:31 UTC Sunday
    - cron: "11 6 * * 1,2,3,4,5,6" # 6:31 UTC Monday-Saturday
  workflow_call:
  workflow_dispatch:
    inputs:
      images:
        description: "Images Build"
        default: '["ucore-hci"]'
        type: choice
        options:
          - '["ucore-minimal"]'
          - '["ucore"]'
          - '["ucore-hci"]'
          - '["ucore-minimal", "ucore", "ucore-hci"]'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-image-server:
    name: Build Server Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        images: ${{ fromJson(inputs.images || '["ucore-minimal", "ucore", "ucore-hci"]') }}
        flavor:
          - main
          - nvidia
    with:
      images: ${{ matrix.images }}
      stream: stable
      flavor: ${{ matrix.flavor }}
